# Generated by Django 2.0.6 on 2018-06-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homeDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=30)),
                ('device_status', models.CharField(max_length=30)),
                ('device_operator', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='logintable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('usertype', models.CharField(max_length=30)),
                ('userstatus', models.CharField(max_length=30)),
            ],
        ),
    ]
