# Generated by Django 2.0.6 on 2018-06-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='userstatus',
            field=models.CharField(default='Active', max_length=30),
        ),
    ]
